#pragma once

#define NFRAME_DEFAULT_FLAGS					(0)
#define NFRAME_DEFAULT_NON_DECORATED_FLAGS		(NFRAME_FLAG_DISABLE_TITLE_BAR | NFRAME_FLAG_DISABLE_SHADOW)

#define NFRAME_FLAG_DISABLE_TITLE_BAR			1
#define NFRAME_FLAG_HIDE_CLOSE_BUTTON			2
#define NFRAME_FLAG_DISABLE_SHADOW				4
#define NFRAME_FLAG_DISABLE_DEFAULT_PAINTER		8
#define NFRAME_FLAG_DISABLE_CLOSE_BUTTON		16